<a href="https://colab.research.google.com/github/sandesh-py/DeepLearning_Lab2026/blob/main/Multilayer_Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# XOR dataset
X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

y = np.array([
    [0],
    [1],
    [1],
    [0]
])

# Sigmoid activation
def sigmoid(x):
    return 1/(1 + np.exp(-x))

# Derivative of sigmoid
def sigmoid_derivative(x):
    return x*(1-x)

np.random.seed(0)

# Weights initialization
W1 = np.random.uniform(-1,1,(2,4))   # input → hidden
b1 = np.zeros((1,4))

W2 = np.random.uniform(-1,1,(4,1))   # hidden → output
b2 = np.zeros((1,1))

learning_rate = 0.5
epochs = 20000

for epoch in range(epochs):

    # Forward pass
    hidden_input = np.dot(X, W1) + b1
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, W2) + b2
    final_output = sigmoid(final_input)

    # Error
    error = y - final_output

    # Backpropagation
    d_output = error * sigmoid_derivative(final_output)

    error_hidden = np.dot(d_output, W2.T)
    d_hidden = error_hidden * sigmoid_derivative(hidden_output)

    # Update weights
    W2 += np.dot(hidden_output.T, d_output) * learning_rate
    b2 += np.sum(d_output, axis=0, keepdims=True) * learning_rate

    W1 += np.dot(X.T, d_hidden) * learning_rate
    b1 += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate

    # Print loss
    if epoch % 5000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Final predictions
print("\nFinal Predictions:")
print(final_output)

Epoch 0, Loss: 0.2749793750132488
Epoch 5000, Loss: 0.000939533226651874
Epoch 10000, Loss: 0.000325192542745722
Epoch 15000, Loss: 0.00019365482022145315

Final Predictions:
[[0.01232113]
 [0.98837102]
 [0.98893206]
 [0.01179401]]


In [ ]:
import numpy as np

# XOR dataset
X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

y = np.array([
    [0],
    [1],
    [1],
    [0]
])

# ReLU activation
def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return np.where(x > 0, 1, 0)

np.random.seed(0)

# Weights initialization
W1 = np.random.uniform(-1,1,(2,4))   # input → hidden
b1 = np.zeros((1,4))

W2 = np.random.uniform(-1,1,(4,1))   # hidden → output
b2 = np.zeros((1,1))

learning_rate = 0.01
epochs = 20000

for epoch in range(epochs):

    # Forward pass
    hidden_input = np.dot(X, W1) + b1
    hidden_output = relu(hidden_input)   # ReLU hidden

    final_input = np.dot(hidden_output, W2) + b2
    final_output = relu(final_input)     # ReLU output

    # Error
    error = y - final_output

    # Backpropagation
    d_output = error * relu_derivative(final_output)

    error_hidden = np.dot(d_output, W2.T)
    d_hidden = error_hidden * relu_derivative(hidden_output)

    # Update weights
    W2 += np.dot(hidden_output.T, d_output) * learning_rate
    b2 += np.sum(d_output, axis=0, keepdims=True) * learning_rate

    W1 += np.dot(X.T, d_hidden) * learning_rate
    b1 += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate

    # Print loss
    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Final predictions (apply threshold)
print("\nFinal Predictions (thresholded):")
print((final_output > 0.5).astype(int))

Epoch 0, Loss: 0.4456710381987794
Epoch 1000, Loss: 0.0002747999823357977
Epoch 2000, Loss: 2.4168287192699798e-08
Epoch 3000, Loss: 2.0431196105639903e-12
Epoch 4000, Loss: 1.7277585472512223e-16
Epoch 5000, Loss: 1.4671472067562866e-20
Epoch 6000, Loss: 1.236482050087232e-24
Epoch 7000, Loss: 1.7737278413298316e-28
Epoch 8000, Loss: 4.6568296418631814e-29
Epoch 9000, Loss: 4.6519695466133093e-29
Epoch 10000, Loss: 4.5703864906576746e-29
Epoch 11000, Loss: 4.6266157194246705e-29
Epoch 12000, Loss: 4.5549307061274245e-29
Epoch 13000, Loss: 4.5971260664184816e-29
Epoch 14000, Loss: 4.641507759517598e-29
Epoch 15000, Loss: 4.5593602521521486e-29
Epoch 16000, Loss: 4.625573187447018e-29
Epoch 17000, Loss: 4.5540931523066107e-29
Epoch 18000, Loss: 4.568580023781789e-29
Epoch 19000, Loss: 4.640415801360909e-29

Final Predictions (thresholded):
[[0]
 [1]
 [1]
 [0]]


In [ ]:
import numpy as np

# XOR dataset (one-hot labels for 2 classes)
X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

y = np.array([
    [1,0],  # class 0
    [0,1],  # class 1
    [0,1],  # class 1
    [1,0]   # class 0
])

# Tanh activation and derivative
def tanh(x):
    return np.tanh(x)

def tanh_derivative(x):
    return 1 - np.tanh(x)**2

# Mean squared error loss
def mse(y_true, y_pred):
    return np.mean((y_true - y_pred)**2)

np.random.seed(0)

# Weights initialization
W1 = np.random.uniform(-1,1,(2,4))   # input → hidden
b1 = np.zeros((1,4))

W2 = np.random.uniform(-1,1,(4,2))   # hidden → output (2 classes)
b2 = np.zeros((1,2))

learning_rate = 0.1
epochs = 20000

for epoch in range(epochs):
    # Forward pass
    hidden_input = np.dot(X, W1) + b1
    hidden_output = tanh(hidden_input)   # <-- tanh activation

    final_input = np.dot(hidden_output, W2) + b2
    final_output = final_input           # <-- linear output (no softmax)

    # Loss
    loss = mse(y, final_output)

    # Backpropagation
    d_output = (final_output - y)        # derivative of MSE wrt output
    error_hidden = np.dot(d_output, W2.T)
    d_hidden = error_hidden * tanh_derivative(hidden_input)

    # Update weights
    W2 -= np.dot(hidden_output.T, d_output) * learning_rate
    b2 -= np.sum(d_output, axis=0, keepdims=True) * learning_rate

    W1 -= np.dot(X.T, d_hidden) * learning_rate
    b1 -= np.sum(d_hidden, axis=0, keepdims=True) * learning_rate

    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, Loss: {loss}")

# Final predictions
print("\nFinal Predictions:")
print(np.argmax(final_output, axis=1))

Epoch 0, Loss: 0.8246403596437153
Epoch 1000, Loss: 3.672459669323642e-24
Epoch 2000, Loss: 1.935559594109172e-31
Epoch 3000, Loss: 1.935559594109172e-31
Epoch 4000, Loss: 1.935559594109172e-31
Epoch 5000, Loss: 1.935559594109172e-31
Epoch 6000, Loss: 1.935559594109172e-31
Epoch 7000, Loss: 1.935559594109172e-31
Epoch 8000, Loss: 1.935559594109172e-31
Epoch 9000, Loss: 1.935559594109172e-31
Epoch 10000, Loss: 1.935559594109172e-31
Epoch 11000, Loss: 1.935559594109172e-31
Epoch 12000, Loss: 1.935559594109172e-31
Epoch 13000, Loss: 1.935559594109172e-31
Epoch 14000, Loss: 1.935559594109172e-31
Epoch 15000, Loss: 1.935559594109172e-31
Epoch 16000, Loss: 1.935559594109172e-31
Epoch 17000, Loss: 1.935559594109172e-31
Epoch 18000, Loss: 1.935559594109172e-31
Epoch 19000, Loss: 1.935559594109172e-31

Final Predictions:
[0 1 1 0]


In [ ]:
4433 r|

SyntaxError: invalid syntax (2005543663.py, line 1)